# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0002_remove_chinesesentence_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chinesesentence',
            old_name='chinese_sentece',
            new_name='chinese_sentence',
        ),
    ]
