# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0004_chinesesentence_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chinesesentence',
            name='lesson',
        ),
    ]
