# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_sentence', models.TextField()),
                ('english_meaning', models.TextField()),
                ('pinyin', models.TextField()),
                ('chinese_sentence', models.TextField()),
                ('lesson_number', models.TextField(default='One')),
            ],
        ),
    ]
